#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=GcdUnit
export drc_rule_deck=calibre-drc-block.rule
export drc_env_setup=undefined

# Commands

if [ -f "inputs/adk/undefined" ]; then source inputs/adk/undefined; fi
envsubst < drc.runset.template > drc.runset
calibre -gui -drc -batch -runset drc.runset
mkdir -p outputs && cd outputs
ln -sf ../drc.results
ln -sf ../drc.summary

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

