build_dir: 2-info
build_id: '2'
commands:
- echo "Design name      -- $design_name"
- echo "Clock period     -- $clock_period"
- echo "ADK              -- $adk"
- echo "ADK view         -- $adk_view"
- echo
- echo "Constructed from -- $construct_path"
- echo
edges_i: {}
edges_o: {}
name: info
parameters:
  adk: asap7
  adk_view: view-standard
  clock_period: 2000.0
  construct_path: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/designs/matrix_mult_2x2x1/construct-commercial-full.py
  design_name: GcdUnit
source: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/steps/info
