build_dir: 0-asap-7-adk
build_id: '0'
commands:
- mkdir -p outputs && cd outputs
- ln -sf ../view-standard adk
edges_i: {}
edges_o:
  adk:
  - f: adk
    step: 5-cadence-genus-synthesis
  - f: adk
    step: 6-cadence-innovus-flowsetup
  - f: adk
    step: 8-cadence-innovus-init
  - f: adk
    step: 9-cadence-innovus-power
  - f: adk
    step: 10-cadence-innovus-place
  - f: adk
    step: 11-cadence-innovus-cts
  - f: adk
    step: 12-cadence-innovus-postcts_hold
  - f: adk
    step: 13-cadence-innovus-route
  - f: adk
    step: 14-cadence-innovus-postroute
  - f: adk
    step: 15-cadence-innovus-postroute_hold
  - f: adk
    step: 16-cadence-innovus-signoff
  - f: adk
    step: 18-synopsys-pt-timing-signoff
  - f: adk
    step: 17-mentor-calibre-gdsmerge
  - f: adk
    step: 22-mentor-calibre-drc
  - f: adk
    step: 23-mentor-calibre-lvs
  - f: adk
    step: 19-synopsys-ptpx-genlibdb
  - f: adk
    step: 25-cadence-innovus-debug-calibre
  - f: adk
    step: 20-synopsys-vcs-sim
  - f: adk
    step: 24-synopsys-pt-power
  - f: adk
    step: 7-verif_post_synth
  - f: adk
    step: 21-verif_post_layout
name: asap-7-adk
outputs:
- adk
parameters:
  adk: asap7
  adk_view: view-standard
sandbox: true
source: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/adks/asap7
