build_dir: 1-constraints
build_id: '1'
commands:
- 'true'
edges_i: {}
edges_o:
  constraints.tcl:
  - f: constraints.tcl
    step: 5-cadence-genus-synthesis
name: constraints
outputs:
- constraints.tcl
parameters:
  clock_period: 2000.0
  design_name: GcdUnit
source: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/steps/constraints
