build_dir: 3-rtl
build_id: '3'
commands:
- 'true'
edges_i: {}
edges_o:
  design.sv:
  - f: design.sv
    step: 5-cadence-genus-synthesis
  - f: design.ref.v
    step: 7-verif_post_synth
name: rtl
outputs:
- design.sv
source: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/designs/matrix_mult_2x2x1/rtl
