#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export design_name=GcdUnit
export saif_instance=GcdUnitTb/GcdUnit_inst
export analysis_mode=averaged
export zero_delay_simulation=False
export lib_op_condition=undefined
export order=designer-interface.tcl,setup-session.tcl,read-design.tcl,report-timing.tcl,report-power.tcl

# Debug

source debug.sh

