build_dir: 5-cadence-genus-synthesis
build_id: '5'
commands:
- genus -no_gui -f START.tcl -log logs/genus.log
- mkdir -p outputs && cd outputs
- ln -sf ../results_syn/syn_out.v design.v
- ln -sf ../results_syn/syn_out._default_constraint_mode_.sdc design.sdc
- ln -sf ../results_syn/syn_out.sdf design.sdf
- ln -sf ../results_syn/syn_out.spef design.spef
- ln -sf ../name_map.rpt design.namemap
debug:
- genus -no_gui -f results_syn/syn_out.genus_setup.tcl
edges_i:
  adk:
  - f: adk
    step: 0-asap-7-adk
  constraints.tcl:
  - f: constraints.tcl
    step: 1-constraints
  design.sv:
  - f: design.sv
    step: 3-rtl
edges_o:
  design.sdc:
  - f: design.sdc
    step: 6-cadence-innovus-flowsetup
  - f: design.sdc
    step: 8-cadence-innovus-init
  - f: design.sdc
    step: 9-cadence-innovus-power
  - f: design.sdc
    step: 10-cadence-innovus-place
  - f: design.sdc
    step: 11-cadence-innovus-cts
  design.v:
  - f: design.v
    step: 6-cadence-innovus-flowsetup
  - f: design.v
    step: 8-cadence-innovus-init
  - f: design.impl.v
    step: 7-verif_post_synth
  - f: design.ref.v
    step: 21-verif_post_layout
inputs:
- adk
- design.sv
- constraints.tcl
name: cadence-genus-synthesis
outputs:
- design.v
- design.sdc
- design.sdf
- design.spef
- design.namemap
parameters:
  clock_period: 2000.0
  design_name: GcdUnit
  flatten_effort: 0
  gate_clock: true
  order:
  - designer-interface.tcl
  - setup-session.tcl
  - read-design.tcl
  - constraints.tcl
  - compile.tcl
  - generate-results.tcl
  read_hdl_defines: ''
  uniquify_with_design_name: true
postconditions:
- assert File( 'outputs/design.v' )
- assert File( 'outputs/design.sdc' )
- assert File( 'outputs/design.sdf' )
- assert File( 'outputs/design.spef' )
- assert 'Cannot resolve reference' not in File( 'logs/genus.log' )
- assert 'Error   :' not in File( 'logs/genus.log' )
#- assert 'create_clock' in File( 'outputs/design.sdc' )
preconditions:
- assert Tool( 'genus' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.sv' )
- assert File( 'inputs/constraints.tcl' )
source: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/steps/cadence-genus-synthesis
