#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export design_name=GcdUnit
export clock_period=2000.0
export gate_clock=True
export uniquify_with_design_name=True
export flatten_effort=0
export read_hdl_defines=
export order=designer-interface.tcl,setup-session.tcl,read-design.tcl,constraints.tcl,compile.tcl,generate-results.tcl

# Debug

genus -no_gui -f results_syn/syn_out.genus_setup.tcl

