#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export testbench_name=GcdUnitTb
export dut_name=GcdUnit_inst
export waveform=True

# Commands

./run.sh

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

