build_dir: 16-cadence-innovus-signoff
build_id: '16'
commands:
- ln -sf inputs/innovus-foundation-flow
- innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log
- cd outputs
- ln -sf ../checkpoints/design.checkpoint
- ln -sf ../typical.spef.gz             design.spef.gz
- ln -sf ../rcbest.spef.gz             design.rcbest.spef.gz
- ln -sf ../results/*.gds.gz            design.gds.gz
- ln -sf ../results/*-merged.gds        design-merged.gds
- ln -sf ../results/*.lvs.v             design.lvs.v
- ln -sf ../results/*.vcs.v             design.vcs.v
- ln -sf ../results/*.vcs.pg.v          design.vcs.pg.v
- ln -sf ../results/*.lef               design.lef
- ln -sf ../results/*.pt.sdc            design.pt.sdc
- ln -sf ../results/*.sdf               design.sdf
- ln -sf ../results/*.virtuoso.v        design.virtuoso.v
- ln -sf ../results/*.def.gz            design.def.gz
debug:
- innovus -overwrite -64 -init innovus-foundation-flow/custom-scripts/run-debug.tcl
  -log logs/debug.log
edges_i:
  adk:
  - f: adk
    step: 0-asap-7-adk
  design.checkpoint:
  - f: design.checkpoint
    step: 15-cadence-innovus-postroute_hold
  innovus-foundation-flow:
  - f: innovus-foundation-flow
    step: 6-cadence-innovus-flowsetup
edges_o:
  design.checkpoint:
  - f: design.checkpoint
    step: 25-cadence-innovus-debug-calibre
  design.gds.gz:
  - f: design.gds.gz
    step: 17-mentor-calibre-gdsmerge
  design.lvs.v:
  - f: design.lvs.v
    step: 23-mentor-calibre-lvs
  - f: design.impl.v
    step: 21-verif_post_layout
  design.pt.sdc:
  - f: design.pt.sdc
    step: 18-synopsys-pt-timing-signoff
  - f: design.pt.sdc
    step: 19-synopsys-ptpx-genlibdb
  - f: design.pt.sdc
    step: 24-synopsys-pt-power
  design.sdf:
  - f: design.sdf
    step: 20-synopsys-vcs-sim
  design.spef.gz:
  - f: design.spef.gz
    step: 18-synopsys-pt-timing-signoff
  - f: design.spef.gz
    step: 19-synopsys-ptpx-genlibdb
  - f: design.spef.gz
    step: 24-synopsys-pt-power
  design.vcs.v:
  - f: design.vcs.v
    step: 18-synopsys-pt-timing-signoff
  - f: design.vcs.v
    step: 19-synopsys-ptpx-genlibdb
  - f: design.vcs.v
    step: 20-synopsys-vcs-sim
  - f: design.vcs.v
    step: 24-synopsys-pt-power
inputs:
- innovus-foundation-flow
- adk
- design.checkpoint
name: cadence-innovus-signoff
outputs:
- design.checkpoint
- design.gds.gz
- design-merged.gds
- design.lvs.v
- design.vcs.v
- design.vcs.pg.v
- design.lef
- design.pt.sdc
- design.sdf
- design.virtuoso.v
- design.spef.gz
- design.rcbest.spef.gz
- design.def.gz
parameters:
  order:
  - main.tcl
  - generate-results.tcl
  - reporting.tcl
postconditions:
- assert File( 'outputs/design.checkpoint' )
preconditions:
- assert Tool( 'innovus' )
- assert File( 'inputs/innovus-foundation-flow' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.checkpoint' )
source: /afs/ece.cmu.edu/usr/edubbers/private/research_work/my_mflowgen/mflowgen/steps/cadence-innovus-signoff
